import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Activity, Target, Sparkles, AlertCircle } from 'lucide-react';

export const InfoSection = ({ title, subtitle, steps, theme = 'rose' }) => {
  const themeColors = {
    rose: { text: 'text-[#FF6B9D]', bg: 'bg-[#FF6B9D]/10', border: 'border-[#FF6B9D]/20' },
    amber: { text: 'text-[#FFB84D]', bg: 'bg-[#FFB84D]/10', border: 'border-[#FFB84D]/20' },
    emerald: { text: 'text-[#17B8A0]', bg: 'bg-[#17B8A0]/10', border: 'border-[#17B8A0]/20' },
    indigo: { text: 'text-[#C084FC]', bg: 'bg-[#C084FC]/10', border: 'border-[#C084FC]/20' },
    sage: { text: 'text-[#17B8A0]', bg: 'bg-[#17B8A0]/10', border: 'border-[#17B8A0]/20' }
  };

  const currentTheme = themeColors[theme];

  return (_jsxs("div", { className: "w-full space-y-6", children: [_jsxs("div", { className: "px-1 space-y-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Target, { className: `w-4 h-4 ${currentTheme.text}` }), _jsx("span", { className: "text-[10px] font-black tracking-[0.2em] uppercase text-slate-400", children: subtitle })] }), _jsx("h2", { className: "text-3xl font-black tracking-tighter text-slate-900 uppercase leading-none whitespace-normal break-words", children: title })] }), _jsx("div", { className: "side-scroller no-scrollbar px-1", children: steps.map((step, idx) => (_jsxs("div", { className: "w-[300px] p-7 card-vibrant border-none bg-white flex flex-col gap-6 shadow-xl shadow-slate-200/40", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `w-11 h-11 rounded-xl flex items-center justify-center font-black text-base shrink-0 ${currentTheme.bg} ${currentTheme.text}`, children: idx + 1 }), _jsx("h3", { className: "text-xl font-black tracking-tight text-slate-800 uppercase leading-tight whitespace-normal break-words", children: step.title })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Activity, { className: "w-4 h-4 text-slate-900" }), _jsx("span", { className: "text-[10px] font-bold uppercase tracking-widest text-slate-900", children: "THE PROTOCOL" })] }), _jsx("p", { className: "text-[15px] font-semibold text-slate-700 leading-snug", children: step.description })] }), _jsx("div", { className: "bg-slate-50 p-4 rounded-2xl border border-slate-100 italic", children: _jsxs("p", { className: "text-xs font-medium text-slate-500 leading-relaxed", children: ["\"", step.importance, "\""] }) }), _jsxs("div", { className: "grid grid-cols-2 gap-4 pt-5 border-t border-slate-100 mt-auto", children: [_jsxs("div", { className: "space-y-1.5", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx(Sparkles, { className: "w-3 h-3 text-[#17B8A0]" }), _jsx("span", { className: "text-[9px] font-black uppercase text-slate-400 tracking-widest block", children: "BENEFIT" })] }), _jsx("p", { className: "text-[11px] font-black text-[#17B8A0] uppercase leading-tight whitespace-normal break-words", children: step.pros[0] })] }), _jsxs("div", { className: "space-y-1.5 text-right border-l border-slate-100 pl-4", children: [_jsxs("div", { className: "flex items-center gap-1.5 justify-end", children: [_jsx("span", { className: "text-[9px] font-black uppercase text-slate-400 tracking-widest block", children: "CAUTION" }), _jsx(AlertCircle, { className: "w-3 h-3 text-[#FF6B9D]" })] }), _jsx("p", { className: "text-[11px] font-black text-[#FF6B9D] uppercase leading-tight whitespace-normal break-words", children: step.cons[0] })] })] })] }, idx))) })] }));
};
